# Generated by Django 5.0.6 on 2024-12-20 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_alter_articleview_unique_together_and_more"),
        ("bookmarks", "0002_alter_bookmark_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="articles.article",
            ),
        ),
    ]
