# Generated by Django 5.0.6 on 2024-12-28 11:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_category(apps, schema_editor):
    User = apps.get_model("user", "User")
    BookmarkCategory = apps.get_model("bookmarks", "BookmarkCategory")

    for user in User.objects.all():
        BookmarkCategory.objects.create(user=user, title="Reading list")


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0003_alter_bookmark_article"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookmarkCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "pkid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=60)),
                ("description", models.TextField(blank=True)),
                ("is_private", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmark_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="bookmarkcategory",
            constraint=models.UniqueConstraint(
                fields=("title", "user"), name="unique_title_per_user"
            ),
        ),
        migrations.RunPython(create_default_category),
    ]
