# Generated by Django 5.0.6 on 2024-12-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0005_bookmarkcategory_is_reading_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmarkcategory",
            name="is_reading_list",
            field=models.BooleanField(default=False),
        ),
    ]
