# Generated by Django 5.0.6 on 2024-12-28 15:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0006_alter_bookmarkcategory_is_reading_list"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookmarksInCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bookmark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_categories",
                        to="bookmarks.bookmark",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "BookmarksInCategories",
            },
        ),
        migrations.CreateModel(
            name="ReadingCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "pkid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=60)),
                ("description", models.TextField(blank=True)),
                ("is_private", models.BooleanField(default=False)),
                ("is_reading_list", models.BooleanField(default=False)),
                (
                    "bookmarks",
                    models.ManyToManyField(
                        through="bookmarks.BookmarksInCategories",
                        to="bookmarks.bookmark",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmark_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ReadingCategories",
            },
        ),
        migrations.AddField(
            model_name="bookmarksincategories",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarked",
                to="bookmarks.readingcategory",
            ),
        ),
        migrations.DeleteModel(
            name="BookmarkCategory",
        ),
        migrations.AddConstraint(
            model_name="readingcategory",
            constraint=models.UniqueConstraint(
                fields=("title", "user"), name="unique_title_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmarksincategories",
            constraint=models.UniqueConstraint(
                fields=("category", "bookmark"), name="unique_boomark_per_category"
            ),
        ),
    ]
