# Generated by Django 5.0.6 on 2024-12-28 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0007_bookmarksincategories_readingcategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmarksincategories",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="bookmarks.readingcategory",
            ),
        ),
    ]
