# Generated by Django 5.0.6 on 2024-12-29 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_article_responses_count"),
        ("bookmarks", "0009_update_existing_bookmarks_to_default_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmarksincategories",
            name="bookmark",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reading_categories",
                to="articles.article",
            ),
        ),
        migrations.AlterField(
            model_name="readingcategory",
            name="bookmarks",
            field=models.ManyToManyField(
                through="bookmarks.BookmarksInCategories", to="articles.article"
            ),
        ),
        migrations.DeleteModel(
            name="Bookmark",
        ),
    ]
