# Generated by Django 5.0.6 on 2024-12-29 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0010_alter_bookmarksincategories_bookmark_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readingcategory",
            name="title",
            field=models.CharField(
                max_length=60, validators=[django.core.validators.MinLengthValidator(1)]
            ),
        ),
    ]
