# Generated by Django 5.0.6 on 2024-12-30 07:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0012_readingcategory_bookmarks_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="readingcategory",
            options={
                "ordering": ["-is_reading_list", "-bookmarks_count"],
                "verbose_name_plural": "ReadingCategories",
            },
        ),
    ]
