# Generated by Django 5.0.6 on 2024-12-30 14:26

import autoslug.fields
from django.db import migrations

import core.utils.hash


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0014_alter_readingcategory_add_slug_field"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="readingcategory",
            name="unique_title_per_user",
        ),
        migrations.AlterField(
            model_name="readingcategory",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                editable=False,
                populate_from=core.utils.hash.generate_hashed_slug,
                unique=True,
            ),
        ),
    ]
