# Generated by Django 5.0.6 on 2025-01-01 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0015_remove_readingcategory_unique_title_per_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="readingcategory",
            options={
                "ordering": ["-is_reading_list"],
                "verbose_name_plural": "ReadingCategories",
            },
        ),
        migrations.RemoveField(
            model_name="readingcategory",
            name="bookmarks_count",
        ),
    ]
