# Generated by Django 5.0.6 on 2025-01-03 06:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0016_alter_readingcategory_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="readingcategory",
            old_name="id",
            new_name="temp_id",
        ),
    ]
