# Generated by Django 5.0.6 on 2025-01-03 06:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0017_rename_id_readingcategory_temp_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="readingcategory",
            old_name="pkid",
            new_name="id",
        ),
    ]
