# Generated by Django 5.0.6 on 2025-02-13 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0014_alter_article_options"),
        ("bookmarks", "0019_rename_temp_id_readingcategory_pkid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmarksincategories",
            name="bookmark",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="articles.article"
            ),
        ),
        migrations.AlterField(
            model_name="readingcategory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reading_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
