# Generated by Django 5.2.1 on 2026-01-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0016_alter_article_managers"),
        ("bookmarks", "0020_alter_bookmarksincategories_bookmark_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readingcategory",
            name="bookmarks",
            field=models.ManyToManyField(
                related_name="category",
                through="bookmarks.BookmarksInCategories",
                to="articles.article",
            ),
        ),
    ]
