import pytest

pytestmark = pytest.mark.django_db


def test_article_view_model__create_instance_successful(
    article_view_factory, normal_user, ipv4
):
    article_view = article_view_factory.create()
    # Default behavior
    assert article_view.article is not None
    assert article_view.user is None
    assert article_view.viewer_ip is None

    # With user and viwer_ip generated by factory
    article_view_2 = article_view_factory.create(has_viewer_ip=True, has_user=True)
    assert article_view_2.viewer_ip is not None
    assert article_view_2.user is not None

    # Specified user and viewer_ip

    article_view_3 = article_view_factory.create(user=normal_user, viewer_ip=ipv4)
    assert article_view_3.user == normal_user
    assert article_view_3.viewer_ip == ipv4


def test_article_view_model__str_method_correct(article_view_factory):
    article_view = article_view_factory.create(has_viewer_ip=True)

    assert (
        article_view.__str__()
        == f"{article_view.article.title} viewed by user \
            {article_view.user.first_name if article_view.user else 'Anonymous'} from IP {article_view.viewer_ip}"
    )
