services:
  terraform:
    image: hashicorp/terraform:1.6.2
    volumes:
      - ./setup:/tr/setup
      - ./deploy:/tr/deploy
    working_dir: /tr
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_DEFAULT_REGION=ap-northeast-1

      - TR_WORKSPACE=${TR_WORKSPACE}
      - TR_VAR_ecr_repo_proxy_image=${TR_VAR_ecr_repo_proxy_image}
      - TF_VAR_ecr_repo_app_image=${TF_VAR_ecr_repo_app_image}

      - TR_VAR_smtp_email_host_user=${TR_VAR_smtp_email_host_user}
      - TR_VAR_smtp_email_host_password=${TR_VAR_smtp_email_host_password}

      - TR_VAR_db_password=${TR_VAR_db_password}
      - TF_VAR_django_secret_key=${TF_VAR_django_secret_key}
      - TF_VAR_jwt_signing_key=${TF_VAR_jwt_signing_key}
      - TF_VAR_domain=${TF_VAR_domain}
      - TF_VAR_celery_broker_url=${TF_VAR_celery_broker_url}
      - TF_VAR_django_admin_url=${TF_VAR_django_admin_url}

