services:
  terraform:
    image: hashicorp/terraform:1.6.2
    volumes:
      - ./setup:/tr/setup
      - ./deploy:/tr/deploy
    working_dir: /tr
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - DEFAULT_REGION=ap-northeast-1
      - TR_WORKSPACE=${TR_WORKSPACE}