# Generated by Django 5.0.6 on 2025-01-01 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_article_responses_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="responses_count",
        ),
    ]
