# Generated by Django 5.0.6 on 2025-01-03 06:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0006_alter_article_managers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="id",
            new_name="temp_id",
        ),
        migrations.RenameField(
            model_name="articleview",
            old_name="id",
            new_name="temp_id",
        ),
        migrations.RenameField(
            model_name="clap",
            old_name="id",
            new_name="temp_id",
        ),
    ]
