# Generated by Django 5.0.6 on 2025-01-03 06:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0007_rename_id_article_temp_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="pkid",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="articleview",
            old_name="pkid",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="clap",
            old_name="pkid",
            new_name="id",
        ),
    ]
