# Generated by Django 5.0.6 on 2025-01-03 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0008_rename_pkid_article_id_rename_pkid_articleview_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="temp_id",
            new_name="pkid",
        ),
        migrations.RenameField(
            model_name="articleview",
            old_name="temp_id",
            new_name="pkid",
        ),
        migrations.RenameField(
            model_name="clap",
            old_name="temp_id",
            new_name="pkid",
        ),
    ]
