# Generated by Django 5.0.6 on 2025-01-10 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0009_rename_temp_id_article_pkid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-created_at"]},
        ),
    ]
