# Generated by Django 5.0.6 on 2025-01-16 14:20

import autoslug.fields
from django.db import migrations

import core.tools.hash


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0010_alter_article_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                editable=False,
                populate_from=core.tools.hash.generate_hashed_slug,
                unique=True,
            ),
        ),
    ]
