# Generated by Django 5.0.6 on 2025-01-16 14:35

import autoslug.fields
from django.db import migrations

import core.utils.hash


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0011_alter_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                editable=False,
                max_length=255,
                populate_from=core.utils.hash.generate_hashed_slug,
                unique=True,
            ),
        ),
    ]
