# Generated by Django 5.0.6 on 2025-02-03 15:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0013_alter_article_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-created_at", "-updated_at"]},
        ),
    ]
