# Generated by Django 5.0.6 on 2025-02-21 07:56

import functools

from django.db import migrations, models

import core.tools.image


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0014_alter_article_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=functools.partial(
                    core.tools.image.generate_file_path, *(), app_name="articles"
                ),
                verbose_name="Banner Image",
            ),
        ),
    ]
