# Generated by Django 5.2.1 on 2026-01-07 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0015_alter_article_banner_image"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="article",
            managers=[],
        ),
    ]
