#!/usr/bin/env bash

set -o errexit
set -o nounset 
set -o pipefail 

backup_dir=$(dirname $BASH_SOURCE[0])

echo "Current backup directory is: $backup_dir"

source "$backup_dir/_sourced/constants.sh"
source "$backup_dir/_sourced/messages.sh"

echo -e "Current user is $POSTGRES_USER\n"

message_welcome "Backing up the '$POSTGRES_DB' database..."

if [[ $POSTGRES_USER == "postgres" ]]; then 
    message_error "Backing up as user 'postgres' is not allowed.\nAssign 'POSTGRES_USER' env with another name and try again."
    exit 1
fi 

export PGHOST=$POSTGRES_HOST
export PGPORT=$POSTGRES_PORT
export PGUSER=$POSTGRES_USER
export PGPASSWORD=$POSTGRES_PASSWORD
export PGDATABASE=$POSTGRES_DB


backup_filename="${BACKUP_FILE_PREFIX}_$(date +'%Y_%m_%dT%H_%M_%S').sql.gz"

pg_dump | gzip > "${DB_BACKUP_DIR_PATH}/${backup_filename}"

message_success "$POSTGRES_DB database backup $backup_filename has been create successfully \
and placed in $DB_BACKUP_DIR_PATH"
