# Generated by Django 5.0.6 on 2025-01-03 06:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="id",
            new_name="temp_id",
        ),
    ]
