# Generated by Django 5.0.6 on 2025-01-03 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_rename_pkid_profile_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="temp_id",
            new_name="pkid",
        ),
    ]
