# Generated by Django 5.0.6 on 2025-01-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_rename_temp_id_profile_pkid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(default="London", verbose_name="city"),
        ),
    ]
