# Generated by Django 5.0.6 on 2025-02-21 07:38

import functools

from django.db import migrations, models

import core.tools.image


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0006_alter_profile_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                default="/profile_default.png",
                upload_to=functools.partial(
                    core.tools.image.generate_file_path, *(), app_name="profiles"
                ),
                verbose_name="profile photo",
            ),
        ),
    ]
