# Generated by Django 5.0.6 on 2025-01-03 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0003_rename_pkid_rating_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="temp_id",
            new_name="pkid",
        ),
    ]
