# Generated by Django 5.0.6 on 2024-12-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("responses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="replies_count",
            field=models.SmallIntegerField(default=0),
        ),
    ]
