# Generated by Django 5.0.6 on 2024-12-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("responses", "0002_response_replies_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="replies_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
