# Generated by Django 5.0.6 on 2024-12-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("responses", "0003_alter_response_replies_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="response",
            options={"ordering": ["claps_count"]},
        ),
        migrations.AddField(
            model_name="response",
            name="claps_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
