# Generated by Django 5.0.6 on 2024-12-25 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_article_responses_count"),
        ("responses", "0008_remove_response_responses_r_claps_c_1597a2_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="response",
            name="responses_r_article_93988d_idx",
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(
                fields=["claps_count"], name="responses_r_claps_c_1597a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(
                fields=["created_at"], name="responses_r_created_a2eb93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(
                fields=["updated_at"], name="responses_r_updated_e50720_idx"
            ),
        ),
    ]
