# Generated by Django 5.0.6 on 2024-12-26 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_article_responses_count"),
        ("responses", "0011_remove_response_responses_r_article_6ae564_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="response",
            name="responses_r_claps_c_9e13e5_idx",
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(
                fields=["claps_count", "created_at"],
                name="responses_r_claps_c_f37071_idx",
            ),
        ),
    ]
