# Generated by Django 5.0.6 on 2025-01-01 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("responses", "0014_remove_response_responses_r_article_6ae564_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="response",
            options={"ordering": ["-created_at", "-updated_at"]},
        ),
        migrations.RemoveIndex(
            model_name="response",
            name="responses_r_parent__e88c44_idx",
        ),
        migrations.RemoveIndex(
            model_name="response",
            name="responses_r_claps_c_9e13e5_idx",
        ),
        migrations.RemoveIndex(
            model_name="response",
            name="responses_r_article_de5547_idx",
        ),
        migrations.RemoveField(
            model_name="response",
            name="claps_count",
        ),
        migrations.RemoveField(
            model_name="response",
            name="replies_count",
        ),
    ]
