# Generated by Django 5.0.6 on 2025-01-03 06:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("responses", "0015_alter_response_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="response",
            old_name="id",
            new_name="temp_id",
        ),
        migrations.RenameField(
            model_name="responseclap",
            old_name="id",
            new_name="temp_id",
        ),
    ]
