# Generated by Django 5.0.6 on 2025-01-03 06:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("responses", "0016_rename_id_response_temp_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="response",
            old_name="pkid",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="responseclap",
            old_name="pkid",
            new_name="id",
        ),
    ]
