#!/bin/bash

set -e

set -o pipefail 

set -o nounset

python -m core.manage wait_for_db
python -m core.manage migrate --no-input
python -m core.manage collectstatic --no-input
python -m core.manage create_superuser

gunicorn --bind 0.0.0.0:8000 --workers 1 core.wsgi
