name: Checks

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

jobs:
  test-lint:
    name: Test and Lint
    uses: ./.github/workflows/test-and-lint.yml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}

      JWT_SIGNING_KEY: ${{ secrets.JWT_SIGNING_KEY }}

      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
