name: Deploy

on:
  push:
    branches: [main, prod]

jobs:
  test-lint:
    uses: ./github/workflows/test-and-lint.yml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      JWT_SIGNING_KEY: ${{ secrets.JWT_SIGNING_KEY }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

  deploy:
    runs-on: ubuntu-latest
    needs: [test-lint]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set Working Space Variables
        run: |
          if [$GITHUB_REF == 'refs/heads/prod' ]; then
            echo "prod" > .workspace
          else 
            echo "main" > .workspace
          fi 
      - name: Push to ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_SECRET_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region ap-northeast-1 | \
          docker login --username AWS --password-stdin ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com
          
          docker build --compress -t ${{ vars.ECR_REPO_APP }}:$GITHUB_SHA docker/prod/django
          docker push ${{ vars.ECR_REPO_APP }}
          docker build --compress -t ${{ vars.ECR_REPO_PROXY }}:$GITHUB_SHA docker/prod/nginx
          docker push ${{ vars.ECR_REPO_PROXY }}


    
